data:
  train_images: ../data/processed/train/images
  train_masks: ../data/processed/train/masks
  val_images: ../data/processed/val/images
  val_masks: ../data/processed/val/masks

training:
  epochs: 10
  batch_size: 2
  learning_rate: 0.0001
  image_size: [512, 512]
  num_classes: 8  
  save_path: ../models/model.pth
